language: node_js
node_js:
  - "14.1.0"
dist: trusty


cache:
  directories:
    - node_modules

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta



before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- ng build

script:
  - npm run lint
  - npm run test
  - npm run build


